version: "3.9"
services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVCONTAINER_OS: ubuntu-22.04
    ports:
      - ${APP_PORT:-8080}:${APP_PORT:-8080}
    volumes:
      - ..:/workspace:cached
      - app-dev-node-modules:/workspace/node_modules
    env_file:
      - ../.env
    command: sleep infinity
    init: true

volumes:
  app-dev-node-modules:
